# Generated by Django 4.2.16 on 2024-09-05 01:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('link', models.URLField()),
                ('code', models.CharField(max_length=300)),
                ('price', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=300)),
                ('total_like', models.IntegerField(default=0)),
                ('likers', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('street', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=20)),
                ('ward', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('is_primary', models.BooleanField()),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='myapp.dish')),
            ],
        ),
        migrations.AddConstraint(
            model_name='address',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('dish',), name='unique_primary_per_dish'),
        ),
    ]
