# Generated by Django 4.2.16 on 2024-09-05 01:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0002_alter_dish_likers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='likers',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
