# Generated by Django 4.2.16 on 2024-09-05 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_dish_likers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='is_primary',
            field=models.BooleanField(default=True),
        ),
    ]
